### ISSUE TITLE
Generation is failling if a GitHub repo is not correctly configurated

### ISSUE THREAD

**Issue by alexislebis** [Humans-of-Julia/StaticWebPages.jl#25]
Generation is failling if a GitHub repo is not correctly configurated, e.g. description or language used are missing

**Comment by Azzaare** [comment]
Thanks @alexislebis 

Sorry for the late messages, I was super busy and just saw all your work now. I am gonna test your PR, and if everything is good, merge them.

Let me know if you plan to add a few more things soon. I will tag a version once you're done!
