### ISSUE TITLE
v0.2.13 layout regression

### ISSUE THREAD

**Issue by alexislebis** [Humans-of-Julia/StaticWebPages.jl#39]
The v0.2.13 release seems to introduce some regression in the layout of various elements (timeline, card) on the page when a block is also present.

I have recompiled your master and still have the issue. I use a classic monitor 1920x1080

![image](https://user-images.githubusercontent.com/12099806/121422717-cba3e200-c96f-11eb-942e-5dfdf10b1dbf.png)

![image](https://user-images.githubusercontent.com/12099806/121422506-97c8bc80-c96f-11eb-99c4-5aa15b8c81ad.png)

**Comment by Azzaare** [comment]
Oh you're right, I will correct this in a couple of hours. (Of course you can go back to 0.2.12 temporary)

Thanks!

**Comment by Azzaare** [comment]
@alexislebis It should be fixed now!

Thank you again for the quick reaction to the previous update ;)

**Comment by alexislebis** [comment]
No worries, always a pleasure :)

Your fix works like a charm in v0.2.14 :+1:
